### ISSUE TITLE
docker-compose configuration for staging/prod

### ISSUE THREAD

**Issue by falconmick** [falconmick/starward#66]
https://github.com/docker/compose/issues/3874#issuecomment-377162033

Production:
`docker-compose -f ./docker-compose.yml -f ./docker-compose.production.yml -f ./docker-compose.overrides.yml`

docker-compose.yml
```
version: '3.6'
services:

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always

  wordpress:
    image: starward-wp:latest
    container_name: wordpress
    volumes:
      - ./projects/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
    links:
      - mysql
    restart: always
  starward:
    image: starward:latest
    container_name: starward
    environment:
      - REDIS_HOST=redis
      - HOST=starward
    depends_on:
      - wordpress
      - mysql
      - redis
    restart: always
    expose:
      - "3000"
    links:
      - redis
      - wordpress
  redis:
    image: redis:4.0.11
    container_name: redis
    restart: always
```

docker-compose.production.yml
```
version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - '80:80'
    - '443:443'
    expose:
    - "80"
    - "433"
    volumes:
    - ./docker/logs/nginx:/var/log/nginx
    links:
    - wordpress
    - starward
    restart: always
```

docker-compose.overrides.yml
```
# to get this working on staging we will need to setup env variables
# per project, see https://github.com/docker/compose/issues/3874#issuecomment-377162033
version: '3.6'
services:
  nginx:
    volumes:
    - ./projects/wordpress:/var/www/html/example.com
    - ./docker/nginx:/etc/nginx/conf.d
    - ./docker/certs:/etc/letsencrypt
    - ./docker/certs-data:/data/letsencrypt

```

for staging all we would do is setup a script that searches for all docker-compose files inside of all sub directories and adds them to the -f chain. We would then have a docker-compose.yml that looks like this in the root that holds all the projects

```
version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - '80:80'
    - '443:443'
    expose:
    - "80"
    - "433"
    volumes:
    - ./docker/logs/nginx:/var/log/nginx
    links:
    - wordpress
    - starward
    restart: always
```

By doing this we are splitting nginx out of the config setup as each project needs to share the nginx setup and thus we don't want it defined in the projects setup UNLESS it's production. add `config` to the end of any command to get the textual output
